var sensor = require('./SensorSuite.js');
var i2c_bus = require('i2c-bus');
//var config = require('./config.json');
var log = function() {};
var i2c = i2c_bus.openSync(1);
var sens = new sensor(i2c, log);
sens.mpu.wakeUp();
sens.mpu.readData();
sens.mpu.convertPosition();
sens.mpu.convettTemp();
sens.mpu.Log();
sens.mpu.sleep();
